export type Category = {
  id: string;
  slug: string;
  title: string;
  description: string;
  image: string;
  imageAlt: string;
  accent: "forest" | "sand" | "burgundy";
};

export type Book = {
  id: string;
  slug: string;
  title: string;
  author: string;
  authorSlug: string;
  category: string;
  categorySlugs: string[];
  origin: string;
  price: string;
  priceNumber: number;
  rating: number;
  reviews: number;
  cover: string;
  year: string;
  description: string;
  publisher: string;
  pubDate: string;
  pages: number;
  format: string;
  language: string;
  stock: number;
  isBestseller: boolean;
  isNew: boolean;
};

export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "quote"; text: string }
  | { type: "image"; src: string; alt: string; caption: string };

export type Article = {
  id: string;
  slug: string;
  category: string;
  title: string;
  subtitle: string;
  excerpt: string;
  author: string;
  authorSlug?: string;
  date: string;
  readTime: string;
  image: string;
  imageAlt: string;
  content: ArticleBlock[];
  relatedBookIds: string[];
  popular: boolean;
};

export type Author = {
  id: string;
  slug: string;
  name: string;
  role: string;
  image: string;
  imageAlt: string;
  note: string;
  bio: string;
  location: string;
  genres: string[];
};

export type Collection = {
  id: string;
  slug: string;
  title: string;
  copy: string;
  description: string;
  cta: string;
  image: string;
  imageAlt: string;
  accent: "forest" | "sand" | "burgundy";
  bookIds: string[];
};

export type ReadingList = {
  id: string;
  slug: string;
  title: string;
  copy: string;
  description: string;
  curator: string;
  image: string;
  imageAlt: string;
  bookIds: string[];
};

export type Faq = {
  category: string;
  items: { q: string; a: string }[];
};

export type FilterChip = {
  id: string;
  label: string;
};

/* ------------------------------------------------------------------ */
/* Categories                                                          */
/* ------------------------------------------------------------------ */

export const categories: Category[] = [
  {
    id: "african-literature",
    slug: "african-literature",
    title: "African Literature",
    description: "Stories, voices, and perspectives from across the continent.",
    image: "/images/col-african-lit.jpg",
    imageAlt: "A stack of well-loved books",
    accent: "forest",
  },
  {
    id: "fiction",
    slug: "fiction",
    title: "Fiction",
    description: "Novels and short stories that move, challenge and stay with you.",
    image: "/images/art-new-writers.jpg",
    imageAlt: "Woman reading intently",
    accent: "burgundy",
  },
  {
    id: "nonfiction",
    slug: "nonfiction",
    title: "Nonfiction",
    description: "True stories, essays and ideas grounded in the real world.",
    image: "/images/cat-nonfiction.jpg",
    imageAlt: "A book resting beside a green plant",
    accent: "forest",
  },
  {
    id: "poetry",
    slug: "poetry",
    title: "Poetry",
    description: "Language at its sharpest and most alive.",
    image: "/images/cat-poetry.jpg",
    imageAlt: "A writer's journal and pen",
    accent: "burgundy",
  },
  {
    id: "philosophy",
    slug: "philosophy",
    title: "Philosophy",
    description: "Questions that have outlasted every empire that asked them.",
    image: "/images/cat-philosophy.jpg",
    imageAlt: "Piles of books on a wooden table",
    accent: "forest",
  },
  {
    id: "personal-development",
    slug: "personal-development",
    title: "Personal Development",
    description: "Practical books for building habits, focus and a better self.",
    image: "/images/list-starting.jpg",
    imageAlt: "A book with reading glasses on top",
    accent: "sand",
  },
  {
    id: "business",
    slug: "business",
    title: "Business",
    description: "Ideas for builders, founders and the ambitious.",
    image: "/images/cat-business.jpg",
    imageAlt: "A team working around a table",
    accent: "forest",
  },
  {
    id: "leadership",
    slug: "leadership",
    title: "Leadership",
    description: "On character, courage and the work of leading others.",
    image: "/images/cat-leadership.jpg",
    imageAlt: "A workspace with notebooks",
    accent: "burgundy",
  },
  {
    id: "history",
    slug: "history",
    title: "History",
    description: "The past, told with the urgency of the present.",
    image: "/images/cat-history.jpg",
    imageAlt: "Tall library shelves",
    accent: "forest",
  },
  {
    id: "culture",
    slug: "culture",
    title: "Culture",
    description: "The ideas and stories that shape how a people see themselves.",
    image: "/images/cat-culture.jpg",
    imageAlt: "Neat rows of books on a shelf",
    accent: "sand",
  },
  {
    id: "childrens-books",
    slug: "childrens-books",
    title: "Children's Books",
    description: "First stories for curious young minds.",
    image: "/images/cat-children.jpg",
    imageAlt: "A tidy classroom desk with books",
    accent: "burgundy",
  },
  {
    id: "biography",
    slug: "biography",
    title: "Biography",
    description: "Lives worth studying, told in full.",
    image: "/images/art-becoming.jpg",
    imageAlt: "Book with a cup of coffee",
    accent: "forest",
  },
  {
    id: "essays",
    slug: "essays",
    title: "Essays",
    description: "Short, sharp thinking on books, culture and the world.",
    image: "/images/art-stay-with-us.jpg",
    imageAlt: "Open book resting on a wooden table",
    accent: "sand",
  },
  {
    id: "religion-spirituality",
    slug: "religion-spirituality",
    title: "Religion and Spirituality",
    description: "Books about belief, meaning and the inner life.",
    image: "/images/cat-religion.jpg",
    imageAlt: "An open book in warm light",
    accent: "forest",
  },
];

export const categoryBySlug = (slug: string) =>
  categories.find((c) => c.slug === slug);

/* ------------------------------------------------------------------ */
/* Books                                                               */
/* ------------------------------------------------------------------ */

export const books: Book[] = [
  {
    id: "beautyful-ones",
    slug: "the-beautyful-ones-are-not-yet-born",
    title: "The Beautyful Ones Are Not Yet Born",
    author: "Ayi Kwei Armah",
    authorSlug: "ayi-kwei-armah",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Ghana",
    price: "KES 1,750",
    priceNumber: 1750,
    rating: 4.6,
    reviews: 1284,
    cover: "/images/cover-beautyful.jpg",
    year: "1968",
    description:
      "A haunting portrait of a nameless man in post-independence Ghana who refuses the easy corruption around him. One of the great works of African fiction, it asks how honesty survives in a country learning to be free.",
    publisher: "Heinemann",
    pubDate: "1968",
    pages: 183,
    format: "Paperback",
    language: "English",
    stock: 24,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "grain-of-wheat",
    slug: "a-grain-of-wheat",
    title: "A Grain of Wheat",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 2,100",
    priceNumber: 2100,
    rating: 4.8,
    reviews: 2103,
    cover: "/images/cover-grain-wheat.jpg",
    year: "1967",
    description:
      "Set in the final days before Kenyan independence, Ngũgĩ's masterwork follows a village shaped by the Emergency, betrayal and the hope of freedom. A novel about the private costs of public change.",
    publisher: "Heinemann",
    pubDate: "1967",
    pages: 272,
    format: "Paperback",
    language: "English",
    stock: 31,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "weep-not-child",
    slug: "weep-not-child",
    title: "Weep Not, Child",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 1,450",
    priceNumber: 1450,
    rating: 4.5,
    reviews: 940,
    cover: "/images/cover-weep-not.jpg",
    year: "1964",
    description:
      "Ngũgĩ's debut follows Njoroge, a boy who believes education is the road to a better future, as colonial Kenya is torn apart by the Mau Mau Emergency. A tender story of hope against the odds.",
    publisher: "Heinemann",
    pubDate: "1964",
    pages: 176,
    format: "Paperback",
    language: "English",
    stock: 18,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "kintu",
    slug: "kintu",
    title: "Kintu",
    author: "Jennifer Nansubuga Makumbi",
    authorSlug: "jennifer-nansubuga-makumbi",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Uganda",
    price: "KES 2,300",
    priceNumber: 2300,
    rating: 4.9,
    reviews: 1877,
    cover: "/images/cover-kintu.jpg",
    year: "2014",
    description:
      "A modern classic that reimagines Ugandan history through the cursed bloodline of the Kintu clan. Spanning two centuries and six families, it is epic in scope and intimate in feeling.",
    publisher: "Transit Books",
    pubDate: "2017",
    pages: 446,
    format: "Paperback",
    language: "English",
    stock: 27,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "dragonfly-sea",
    slug: "the-dragonfly-sea",
    title: "The Dragonfly Sea",
    author: "Yvonne Adhiambo Owuor",
    authorSlug: "yvonne-adhiambo-owuor",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 2,500",
    priceNumber: 2500,
    rating: 4.7,
    reviews: 1562,
    cover: "/images/cover-dragonfly.jpg",
    year: "2019",
    description:
      "Ayaana grows up on a small island off the Kenyan coast, her life shaped by the sea and the centuries of trade, faith and longing that move across it. A luminous novel of home and the wide world.",
    publisher: "Knopf",
    pubDate: "2019",
    pages: 512,
    format: "Paperback",
    language: "English",
    stock: 15,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "dust",
    slug: "dust",
    title: "Dust",
    author: "Yvonne Adhiambo Owuor",
    authorSlug: "yvonne-adhiambo-owuor",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 2,250",
    priceNumber: 2250,
    rating: 4.6,
    reviews: 1130,
    cover: "/images/cover-dust.jpg",
    year: "2014",
    description:
      "Beginning with a young man's murder on the day of the 2007 elections, Dust unfolds the history of a family and a splintered nation. A fierce, lyrical novel about Kenya and the wounds it carries.",
    publisher: "Alfred A. Knopf",
    pubDate: "2014",
    pages: 384,
    format: "Paperback",
    language: "English",
    stock: 21,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "decolonising-the-mind",
    slug: "decolonising-the-mind",
    title: "Decolonising the Mind",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Essays",
    categorySlugs: ["essays", "nonfiction", "culture"],
    origin: "Kenya",
    price: "KES 2,000",
    priceNumber: 2000,
    rating: 4.9,
    reviews: 2430,
    cover: "/images/cover-decolonising.jpg",
    year: "1986",
    description:
      "Ngũgĩ's landmark argument that language is the carrier of culture, and that writing in African languages is an act of self-liberation. Essential reading for anyone who thinks about storytelling and power.",
    publisher: "James Currey",
    pubDate: "1986",
    pages: 114,
    format: "Paperback",
    language: "English",
    stock: 40,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "petals-of-blood",
    slug: "petals-of-blood",
    title: "Petals of Blood",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 2,100",
    priceNumber: 2100,
    rating: 4.7,
    reviews: 1221,
    cover: "/images/cover-petals.jpg",
    year: "1977",
    description:
      "Four strangers come together in the Kenyan town of Ilmorog as the country hurtles toward the post-independence betrayals Ngũgĩ chronicles with fury and compassion. A towering political novel.",
    publisher: "Heinemann",
    pubDate: "1977",
    pages: 344,
    format: "Paperback",
    language: "English",
    stock: 19,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "river-between",
    slug: "the-river-between",
    title: "The River Between",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 1,600",
    priceNumber: 1600,
    rating: 4.6,
    reviews: 810,
    cover: "/images/cover-river-between.jpg",
    year: "1965",
    description:
      "Set between two ridges and two worlds, this early Ngũgĩ novel tells of a young man caught between tradition and the new faiths arriving with colonialism. A story of a people at a crossroads.",
    publisher: "Heinemann",
    pubDate: "1965",
    pages: 152,
    format: "Paperback",
    language: "English",
    stock: 14,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "devil-on-the-cross",
    slug: "devil-on-the-cross",
    title: "Devil on the Cross",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 1,950",
    priceNumber: 1950,
    rating: 4.5,
    reviews: 690,
    cover: "/images/cover-devil-cross.jpg",
    year: "1980",
    description:
      "Written secretly on toilet paper in a Kenyan prison, this satirical novel follows a young woman to a gathering of thieves in a cave. A fearless indictment of greed dressed as progress.",
    publisher: "Heinemann",
    pubDate: "1980",
    pages: 256,
    format: "Paperback",
    language: "English",
    stock: 11,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "wizard-of-the-crow",
    slug: "wizard-of-the-crow",
    title: "Wizard of the Crow",
    author: "Ngũgĩ wa Thiong'o",
    authorSlug: "ngugi-wa-thiongo",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Kenya",
    price: "KES 2,800",
    priceNumber: 2800,
    rating: 4.8,
    reviews: 1580,
    cover: "/images/cover-wizard-crow.jpg",
    year: "2006",
    description:
      "Ngũgĩ's epic comic novel of an African dictatorship and the humble trickster who becomes its improbable challenger. A book-length parable about power, exile and the people who survive both.",
    publisher: "Pantheon",
    pubDate: "2006",
    pages: 768,
    format: "Paperback",
    language: "English",
    stock: 12,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "things-fall-apart",
    slug: "things-fall-apart",
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    authorSlug: "chinua-achebe",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Nigeria",
    price: "KES 1,850",
    priceNumber: 1850,
    rating: 4.9,
    reviews: 4210,
    cover: "/images/cover-things-fall-apart.jpg",
    year: "1958",
    description:
      "The novel that changed African writing forever. Okonkwo's story is the story of a man, a village and a world colliding with colonialism. Essential, devastating and endlessly reread.",
    publisher: "Heinemann",
    pubDate: "1958",
    pages: 209,
    format: "Paperback",
    language: "English",
    stock: 35,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "no-longer-at-ease",
    slug: "no-longer-at-ease",
    title: "No Longer at Ease",
    author: "Chinua Achebe",
    authorSlug: "chinua-achebe",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Nigeria",
    price: "KES 1,650",
    priceNumber: 1650,
    rating: 4.4,
    reviews: 610,
    cover: "/images/cover-no-longer-ease.jpg",
    year: "1960",
    description:
      "The sequel to Things Fall Apart follows Obi, grandson of Okonkwo, into a Lagos caught between the old obligations and the new temptations of a rising nation. A sharp study of corruption and conscience.",
    publisher: "Heinemann",
    pubDate: "1960",
    pages: 176,
    format: "Paperback",
    language: "English",
    stock: 13,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "arrow-of-god",
    slug: "arrow-of-god",
    title: "Arrow of God",
    author: "Chinua Achebe",
    authorSlug: "chinua-achebe",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Nigeria",
    price: "KES 1,900",
    priceNumber: 1900,
    rating: 4.7,
    reviews: 870,
    cover: "/images/cover-arrow-god.jpg",
    year: "1964",
    description:
      "Ezeulu, chief priest of Ulu, wages a quiet war of pride with the colonial authorities, and his village pays the price. Achebe's most accomplished novel about faith, power and their human costs.",
    publisher: "Heinemann",
    pubDate: "1964",
    pages: 288,
    format: "Paperback",
    language: "English",
    stock: 9,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "half-of-a-yellow-sun",
    slug: "half-of-a-yellow-sun",
    title: "Half of a Yellow Sun",
    author: "Chimamanda Ngozi Adichie",
    authorSlug: "chimamanda-ngozi-adichie",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Nigeria",
    price: "KES 2,750",
    priceNumber: 2750,
    rating: 4.8,
    reviews: 3540,
    cover: "/images/cover-half-yellow-sun.jpg",
    year: "2006",
    description:
      "Set during the Nigerian-Biafran war, this sweeping novel follows twin sisters and the men who love them through love, loss and the birth of a nation. Adichie's breakout masterpiece.",
    publisher: "Fourth Estate",
    pubDate: "2006",
    pages: 448,
    format: "Paperback",
    language: "English",
    stock: 22,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "purple-hibiscus",
    slug: "purple-hibiscus",
    title: "Purple Hibiscus",
    author: "Chimamanda Ngozi Adichie",
    authorSlug: "chimamanda-ngozi-adichie",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Nigeria",
    price: "KES 1,950",
    priceNumber: 1950,
    rating: 4.6,
    reviews: 1980,
    cover: "/images/cover-purple-hibiscus.jpg",
    year: "2003",
    description:
      "Fifteen-year-old Kambili lives in a house run by a terrifying religious father. The story of her awakening is one of the most assured debuts in modern African fiction.",
    publisher: "Algonquin Books",
    pubDate: "2003",
    pages: 307,
    format: "Paperback",
    language: "English",
    stock: 26,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "americanah",
    slug: "americanah",
    title: "Americanah",
    author: "Chimamanda Ngozi Adichie",
    authorSlug: "chimamanda-ngozi-adichie",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Nigeria",
    price: "KES 2,600",
    priceNumber: 2600,
    rating: 4.7,
    reviews: 2760,
    cover: "/images/cover-americanah.jpg",
    year: "2013",
    description:
      "Ifemelu and Obinze leave Nigeria for America and England, and their love story becomes a sharp, funny and profound account of race, identity and what we carry across borders.",
    publisher: "Alfred A. Knopf",
    pubDate: "2013",
    pages: 477,
    format: "Paperback",
    language: "English",
    stock: 20,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "one-day-i-will-write",
    slug: "one-day-i-will-write-about-this-place",
    title: "One Day I Will Write About This Place",
    author: "Binyavanga Wainaina",
    authorSlug: "binyavanga-wainaina",
    category: "Biography",
    categorySlugs: ["biography", "essays", "culture"],
    origin: "Kenya",
    price: "KES 2,350",
    priceNumber: 2350,
    rating: 4.8,
    reviews: 1520,
    cover: "/images/cover-one-day.jpg",
    year: "2011",
    description:
      "Wainaina's memoir of growing up in Kenya in the 1970s and 80s is by turns hilarious, restless and aching with honesty. A classic of African autobiography and a portrait of a country becoming itself.",
    publisher: "Graywolf Press",
    pubDate: "2011",
    pages: 368,
    format: "Paperback",
    language: "English",
    stock: 16,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "nairobi-heat",
    slug: "nairobi-heat",
    title: "Nairobi Heat",
    author: "Mũkoma wa Ngũgĩ",
    authorSlug: "mukoma-wa-ngugi",
    category: "Fiction",
    categorySlugs: ["fiction"],
    origin: "Kenya",
    price: "KES 1,700",
    priceNumber: 1700,
    rating: 4.3,
    reviews: 470,
    cover: "/images/cover-nairobi-heat.jpg",
    year: "2009",
    description:
      "A dead white woman appears on a Madison doorstep with a note saying she is from Kibera, and detective Ishmael Fofana flies to Nairobi to find out why. A crackling thriller with a conscience.",
    publisher: "Melville House",
    pubDate: "2009",
    pages: 192,
    format: "Paperback",
    language: "English",
    stock: 8,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "mrs-shaw",
    slug: "mrs-shaw",
    title: "Mrs. Shaw",
    author: "Mũkoma wa Ngũgĩ",
    authorSlug: "mukoma-wa-ngugi",
    category: "Fiction",
    categorySlugs: ["fiction"],
    origin: "Kenya",
    price: "KES 1,800",
    priceNumber: 1800,
    rating: 4.2,
    reviews: 310,
    cover: "/images/cover-mrs-shaw.jpg",
    year: "2014",
    description:
      "A novel-in-verse that follows a Kenyan woman exiled from her country and trapped in the wrong life. Tender, furious and formally inventive.",
    publisher: "Ohio University Press",
    pubDate: "2014",
    pages: 160,
    format: "Paperback",
    language: "English",
    stock: 7,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "homegoing",
    slug: "homegoing",
    title: "Homegoing",
    author: "Yaa Gyasi",
    authorSlug: "yaa-gyasi",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Ghana",
    price: "KES 2,400",
    priceNumber: 2400,
    rating: 4.8,
    reviews: 3120,
    cover: "/images/cover-homegoing.jpg",
    year: "2016",
    description:
      "Two half-sisters in eighteenth-century Ghana, one married to an Englishman, the other sold into slavery. Their descendants' stories stretch across three hundred years in a novel of astonishing reach.",
    publisher: "Alfred A. Knopf",
    pubDate: "2016",
    pages: 305,
    format: "Paperback",
    language: "English",
    stock: 23,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "paradise",
    slug: "paradise",
    title: "Paradise",
    author: "Abdulrazak Gurnah",
    authorSlug: "abdulrazak-gurnah",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Tanzania",
    price: "KES 2,150",
    priceNumber: 2150,
    rating: 4.5,
    reviews: 980,
    cover: "/images/cover-paradise.jpg",
    year: "1994",
    description:
      "A young boy is sold into service and travels with a merchant's caravan across a turn-of-the-century East Africa on the eve of colonial conquest. Nobel laureate Gurnah's most celebrated novel.",
    publisher: "Bloomsbury",
    pubDate: "1994",
    pages: 246,
    format: "Paperback",
    language: "English",
    stock: 10,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "afterlives",
    slug: "afterlives",
    title: "Afterlives",
    author: "Abdulrazak Gurnah",
    authorSlug: "abdulrazak-gurnah",
    category: "Fiction",
    categorySlugs: ["african-literature", "fiction"],
    origin: "Tanzania",
    price: "KES 2,650",
    priceNumber: 2650,
    rating: 4.6,
    reviews: 740,
    cover: "/images/cover-afterlives.jpg",
    year: "2020",
    description:
      "Gurnah returns to the coast of German East Africa to tell the lives that wars interrupt and ordinary love quietly restores. Shortlisted for the Nobel that followed soon after.",
    publisher: "Riverhead Books",
    pubDate: "2020",
    pages: 304,
    format: "Paperback",
    language: "English",
    stock: 14,
    isBestseller: false,
    isNew: true,
  },
  {
    id: "song-of-lawino",
    slug: "song-of-lawino",
    title: "Song of Lawino",
    author: "Okot p'Bitek",
    authorSlug: "okot-pbitek",
    category: "Poetry",
    categorySlugs: ["poetry", "culture"],
    origin: "Uganda",
    price: "KES 1,550",
    priceNumber: 1550,
    rating: 4.7,
    reviews: 520,
    cover: "/images/cover-song-lawino.jpg",
    year: "1966",
    description:
      "Lawino sings the complaint of a wife left behind by a husband who has embraced the new ways. A masterpiece of African poetry that turned a divorce quarrel into a debate about culture and identity.",
    publisher: "East African Publishing House",
    pubDate: "1966",
    pages: 216,
    format: "Paperback",
    language: "English",
    stock: 12,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "born-a-crime",
    slug: "born-a-crime",
    title: "Born a Crime",
    author: "Trevor Noah",
    authorSlug: "trevor-noah",
    category: "Biography",
    categorySlugs: ["biography"],
    origin: "South Africa",
    price: "KES 2,950",
    priceNumber: 2950,
    rating: 4.8,
    reviews: 2680,
    cover: "/images/cover-born-a-crime.jpg",
    year: "2016",
    description:
      "Trevor Noah's memoir of growing up in South Africa, where his very birth was a crime, is funny, ferocious and full of heart. A story about a boy and the remarkable mother who raised him.",
    publisher: "Spiegel & Grau",
    pubDate: "2016",
    pages: 304,
    format: "Paperback",
    language: "English",
    stock: 30,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "long-walk-to-freedom",
    slug: "long-walk-to-freedom",
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    authorSlug: "nelson-mandela",
    category: "Biography",
    categorySlugs: ["biography", "history", "leadership"],
    origin: "South Africa",
    price: "KES 3,200",
    priceNumber: 3200,
    rating: 4.9,
    reviews: 3870,
    cover: "/images/cover-long-walk.jpg",
    year: "1994",
    description:
      "The autobiography of Nelson Mandela, from a village childhood to twenty-seven years in prison to the presidency that ended apartheid. The defining account of a life given to a people.",
    publisher: "Little, Brown and Company",
    pubDate: "1994",
    pages: 640,
    format: "Paperback",
    language: "English",
    stock: 28,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "meditations",
    slug: "meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    authorSlug: "marcus-aurelius",
    category: "Philosophy",
    categorySlugs: ["philosophy", "leadership"],
    origin: "Rome",
    price: "KES 1,900",
    priceNumber: 1900,
    rating: 4.7,
    reviews: 2210,
    cover: "/images/cover-meditations.jpg",
    year: "180",
    description:
      "The private notebook of a Roman emperor who asked himself what it means to be good. Two thousand years later it remains the most direct book of practical philosophy ever written.",
    publisher: "Penguin Classics",
    pubDate: "180 AD",
    pages: 256,
    format: "Paperback",
    language: "English",
    stock: 17,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "mans-search-for-meaning",
    slug: "mans-search-for-meaning",
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    authorSlug: "viktor-frankl",
    category: "Philosophy",
    categorySlugs: ["philosophy", "personal-development"],
    origin: "Austria",
    price: "KES 1,850",
    priceNumber: 1850,
    rating: 4.9,
    reviews: 3350,
    cover: "/images/cover-mans-search.jpg",
    year: "1946",
    description:
      "Viktor Frankl survived the camps to write the most influential account of why meaning is the thing that keeps a person alive. A short book with a long, deep reach.",
    publisher: "Beacon Press",
    pubDate: "1946",
    pages: 165,
    format: "Paperback",
    language: "English",
    stock: 34,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "atomic-habits",
    slug: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    authorSlug: "james-clear",
    category: "Personal Development",
    categorySlugs: ["personal-development", "business"],
    origin: "United States",
    price: "KES 2,700",
    priceNumber: 2700,
    rating: 4.8,
    reviews: 4890,
    cover: "/images/cover-atomic-habits.jpg",
    year: "2018",
    description:
      "James Clear's practical framework for building good habits and breaking bad ones, one small change at a time. The most bought self-improvement book of its generation.",
    publisher: "Avery",
    pubDate: "2018",
    pages: 320,
    format: "Hardcover",
    language: "English",
    stock: 25,
    isBestseller: true,
    isNew: false,
  },
  {
    id: "start-with-why",
    slug: "start-with-why",
    title: "Start with Why",
    author: "Simon Sinek",
    authorSlug: "simon-sinek",
    category: "Business",
    categorySlugs: ["business", "leadership"],
    origin: "United Kingdom",
    price: "KES 2,500",
    priceNumber: 2500,
    rating: 4.5,
    reviews: 1760,
    cover: "/images/cover-start-with-why.jpg",
    year: "2009",
    description:
      "Simon Sinek's simple question, why do some people and organisations inspire while others don't, became a global movement. A clear book for builders who want to lead from purpose.",
    publisher: "Portfolio",
    pubDate: "2009",
    pages: 256,
    format: "Hardcover",
    language: "English",
    stock: 16,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "king-leopolds-ghost",
    slug: "king-leopolds-ghost",
    title: "King Leopold's Ghost",
    author: "Adam Hochschild",
    authorSlug: "adam-hochschild",
    category: "History",
    categorySlugs: ["history"],
    origin: "United States",
    price: "KES 2,850",
    priceNumber: 2850,
    rating: 4.7,
    reviews: 1420,
    cover: "/images/cover-king-leopold.jpg",
    year: "1998",
    description:
      "The horrifying story of how one king privately owned and plundered the Congo, and of the first great human rights movement that rose to stop him. A masterpiece of narrative history.",
    publisher: "Houghton Mifflin",
    pubDate: "1998",
    pages: 384,
    format: "Paperback",
    language: "English",
    stock: 13,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "the-prophet",
    slug: "the-prophet",
    title: "The Prophet",
    author: "Kahlil Gibran",
    authorSlug: "kahlil-gibran",
    category: "Religion and Spirituality",
    categorySlugs: ["religion-spirituality", "poetry"],
    origin: "Lebanon",
    price: "KES 1,700",
    priceNumber: 1700,
    rating: 4.6,
    reviews: 1990,
    cover: "/images/cover-prophet.jpg",
    year: "1923",
    description:
      "A prophet, before sailing away, answers twenty-six questions about love, work, joy and sorrow. Gibran's prose poem has become one of the most translated books of the twentieth century.",
    publisher: "Alfred A. Knopf",
    pubDate: "1923",
    pages: 96,
    format: "Hardcover",
    language: "English",
    stock: 18,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "we-should-all-be-feminists",
    slug: "we-should-all-be-feminists",
    title: "We Should All Be Feminists",
    author: "Chimamanda Ngozi Adichie",
    authorSlug: "chimamanda-ngozi-adichie",
    category: "Essays",
    categorySlugs: ["essays", "culture"],
    origin: "Nigeria",
    price: "KES 1,600",
    priceNumber: 1600,
    rating: 4.8,
    reviews: 2140,
    cover: "/images/cover-feminists.jpg",
    year: "2014",
    description:
      "Adichie's brilliant, funny and urgent essay on what feminism means in the twenty-first century, born from her landmark TED talk. Small in size, huge in impact.",
    publisher: "Fourth Estate",
    pubDate: "2014",
    pages: 64,
    format: "Hardcover",
    language: "English",
    stock: 21,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "the-wretched-of-the-earth",
    slug: "the-wretched-of-the-earth",
    title: "The Wretched of the Earth",
    author: "Frantz Fanon",
    authorSlug: "frantz-fanon",
    category: "History",
    categorySlugs: ["history", "philosophy"],
    origin: "Martinique",
    price: "KES 2,400",
    priceNumber: 2400,
    rating: 4.7,
    reviews: 1830,
    cover: "/images/cover-wretched-earth.jpg",
    year: "1961",
    description:
      "Fanon's explosive study of colonialism, violence and decolonisation was written at the end of his life and became the handbook of liberation movements everywhere.",
    publisher: "Grove Press",
    pubDate: "1961",
    pages: 320,
    format: "Paperback",
    language: "English",
    stock: 15,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "the-alchemist",
    slug: "the-alchemist",
    title: "The Alchemist",
    author: "Paulo Coelho",
    authorSlug: "paulo-coelho",
    category: "Fiction",
    categorySlugs: ["fiction", "personal-development", "religion-spirituality"],
    origin: "Brazil",
    price: "KES 2,050",
    priceNumber: 2050,
    rating: 4.6,
    reviews: 2980,
    cover: "/images/cover-alchemist.jpg",
    year: "1988",
    description:
      "A shepherd boy follows his dream across a desert to the Pyramids and finds that the treasure was the journey itself. The world's favourite fable about following your personal legend.",
    publisher: "HarperOne",
    pubDate: "1988",
    pages: 208,
    format: "Paperback",
    language: "English",
    stock: 29,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "a-is-for-africa",
    slug: "a-is-for-africa",
    title: "A Is for Africa",
    author: "Ifeoma Onyefulu",
    authorSlug: "ifeoma-onyefulu",
    category: "Children's Books",
    categorySlugs: ["childrens-books", "culture"],
    origin: "Nigeria",
    price: "KES 1,450",
    priceNumber: 1450,
    rating: 4.6,
    reviews: 290,
    cover: "/images/cover-a-is-for-africa.jpg",
    year: "1993",
    description:
      "A vibrant alphabet book that introduces children to the everyday life of a village in Nigeria, through photographs and the richness of African daily culture. A wonderful first book.",
    publisher: "Frances Lincoln",
    pubDate: "1993",
    pages: 32,
    format: "Picture Book",
    language: "English",
    stock: 20,
    isBestseller: false,
    isNew: false,
  },
  {
    id: "wangaris-trees-of-peace",
    slug: "wangaris-trees-of-peace",
    title: "Wangari's Trees of Peace",
    author: "Jeanette Winter",
    authorSlug: "jeanette-winter",
    category: "Children's Books",
    categorySlugs: ["childrens-books", "culture"],
    origin: "United States",
    price: "KES 1,650",
    priceNumber: 1650,
    rating: 4.7,
    reviews: 180,
    cover: "/images/cover-wangari.jpg",
    year: "2008",
    description:
      "The true story of Wangari Maathai, who began by planting nine trees in her yard and ended by leading a movement that planted millions across Kenya. An inspiring picture book.",
    publisher: "Harcourt",
    pubDate: "2008",
    pages: 32,
    format: "Picture Book",
    language: "English",
    stock: 14,
    isBestseller: false,
    isNew: false,
  },
];

export const getBookBySlug = (slug: string) => books.find((b) => b.slug === slug);
export const getBookById = (id: string) => books.find((b) => b.id === id);

export const booksByAuthor = (authorSlug: string) =>
  books.filter((b) => b.authorSlug === authorSlug);

export const booksByCategory = (categorySlug: string) =>
  books.filter((b) => b.categorySlugs.includes(categorySlug));

export const booksByIds = (ids: string[]) =>
  ids
    .map((id) => getBookById(id))
    .filter((b): b is Book => Boolean(b));

export const featuredBookIds = [
  "beautyful-ones",
  "grain-of-wheat",
  "weep-not-child",
  "kintu",
  "dragonfly-sea",
  "dust",
  "decolonising-the-mind",
  "petals-of-blood",
];

export const featuredBooks = booksByIds(featuredBookIds);

export const newReleases = books.filter((b) => b.isNew);
export const bestsellers = books.filter((b) => b.isBestseller);

/* ------------------------------------------------------------------ */
/* Discovery filters                                                   */
/* ------------------------------------------------------------------ */

export const discoveryFilters: FilterChip[] = [
  { id: "categories", label: "Categories" },
  { id: "authors", label: "Authors" },
  { id: "new-releases", label: "New Releases" },
  { id: "bestsellers", label: "Bestsellers" },
  { id: "reading-lists", label: "Reading Lists" },
];

/* ------------------------------------------------------------------ */
/* Collections                                                         */
/* ------------------------------------------------------------------ */

export const collections: Collection[] = [
  {
    id: "essential-african-literature",
    slug: "essential-african-literature",
    title: "Essential African Literature",
    copy: "Stories from writers across the continent, from the classics to the next generation.",
    description:
      "The books every reader should meet first: the landmarks of African fiction from Achebe and Armah to Adichie and Makumbi.",
    cta: "Browse collection",
    image: "/images/col-african-lit.jpg",
    imageAlt: "A stack of well-loved books",
    accent: "forest",
    bookIds: [
      "things-fall-apart",
      "beautyful-ones",
      "grain-of-wheat",
      "kintu",
      "half-of-a-yellow-sun",
      "homegoing",
      "dragonfly-sea",
      "arrow-of-god",
    ],
  },
  {
    id: "books-that-make-you-think",
    slug: "books-that-make-you-think",
    title: "Books That Make You Think",
    copy: "Ideas, philosophy, culture and perspective for curious, restless minds.",
    description:
      "For readers who like a book to argue back. A shelf of philosophy, essays and ideas that reward slow reading.",
    cta: "Start thinking",
    image: "/images/col-think.jpg",
    imageAlt: "Quiet library reading room",
    accent: "burgundy",
    bookIds: [
      "decolonising-the-mind",
      "meditations",
      "mans-search-for-meaning",
      "the-wretched-of-the-earth",
      "we-should-all-be-feminists",
      "the-prophet",
    ],
  },
  {
    id: "contemporary-kenyan-writing",
    slug: "contemporary-kenyan-writing",
    title: "Contemporary Kenyan Writing",
    copy: "The writers shaping Kenyan letters right now.",
    description:
      "From Owuor to Mũkoma, the new voices carrying Kenyan stories into the twenty-first century.",
    cta: "Explore Kenyan writing",
    image: "/images/list-kenya.jpg",
    imageAlt: "A person browsing shelves in a library",
    accent: "forest",
    bookIds: [
      "dust",
      "dragonfly-sea",
      "nairobi-heat",
      "mrs-shaw",
      "one-day-i-will-write",
    ],
  },
  {
    id: "books-for-your-next-chapter",
    slug: "books-for-your-next-chapter",
    title: "Books for Your Next Chapter",
    copy: "Books about growth, ambition, creativity and the quiet art of becoming.",
    description:
      "A reading list for anyone starting something new, told in the language of habits, purpose and second acts.",
    cta: "Begin a new chapter",
    image: "/images/col-next-chapter.jpg",
    imageAlt: "Piles of books beside a window",
    accent: "sand",
    bookIds: [
      "atomic-habits",
      "start-with-why",
      "the-alchemist",
      "mans-search-for-meaning",
      "one-day-i-will-write",
    ],
  },
  {
    id: "staff-picks",
    slug: "staff-picks",
    title: "Staff Picks",
    copy: "The books our booksellers reach for again and again.",
    description:
      "Hand-picked by the Man Within team, these are the titles that stay on our desks long after the review.",
    cta: "See staff picks",
    image: "/images/art-need-books.jpg",
    imageAlt: "Person reading a book beside a plant",
    accent: "burgundy",
    bookIds: [
      "kintu",
      "petals-of-blood",
      "wizard-of-the-crow",
      "born-a-crime",
      "americanah",
    ],
  },
  {
    id: "new-voices",
    slug: "new-voices",
    title: "New Voices",
    copy: "The writers reimagining African stories for a global readership.",
    description:
      "Debutantes and rising stars whose books we believe will be the classics of tomorrow.",
    cta: "Meet new voices",
    image: "/images/art-new-writers.jpg",
    imageAlt: "Woman reading intently",
    accent: "forest",
    bookIds: [
      "afterlives",
      "homegoing",
      "purple-hibiscus",
      "mrs-shaw",
      "nairobi-heat",
    ],
  },
  {
    id: "books-worth-re-reading",
    slug: "books-worth-re-reading",
    title: "Books Worth Re-reading",
    copy: "Titles that reveal more on the second, third and tenth visit.",
    description:
      "The mark of a great book is that you finish it and immediately think about starting again. These are ours.",
    cta: "Re-read with us",
    image: "/images/list-curious.jpg",
    imageAlt: "Books stacked neatly on top of each other",
    accent: "sand",
    bookIds: [
      "beautyful-ones",
      "grain-of-wheat",
      "weep-not-child",
      "song-of-lawino",
      "the-prophet",
    ],
  },
  {
    id: "reading-for-growth",
    slug: "reading-for-growth",
    title: "Reading for Growth",
    copy: "A shelf for the ambitious, the restless and the about-to-begin.",
    description:
      "Ideas that move you forward: habits, meaning, leadership and the courage to start.",
    cta: "Grow with us",
    image: "/images/list-starting.jpg",
    imageAlt: "A book with reading glasses on top",
    accent: "forest",
    bookIds: [
      "atomic-habits",
      "mans-search-for-meaning",
      "long-walk-to-freedom",
      "start-with-why",
      "the-alchemist",
    ],
  },
];

export const getCollectionBySlug = (slug: string) =>
  collections.find((c) => c.slug === slug);

/* ------------------------------------------------------------------ */
/* Reading lists                                                       */
/* ------------------------------------------------------------------ */

export const readingLists: ReadingList[] = [
  {
    id: "curious-mind",
    slug: "5-books-every-curious-mind-should-read",
    title: "5 Books Every Curious Mind Should Read",
    copy: "A starting point for readers who want to think better.",
    description:
      "Five books that reward curiosity with new questions: philosophy, essays and one unforgettable novel.",
    curator: "Wanjiru Kamau",
    image: "/images/list-curious.jpg",
    imageAlt: "Books stacked neatly on top of each other",
    bookIds: [
      "meditations",
      "mans-search-for-meaning",
      "decolonising-the-mind",
      "we-should-all-be-feminists",
      "kintu",
    ],
  },
  {
    id: "contemporary-african-fiction",
    slug: "contemporary-african-fiction",
    title: "Contemporary African Fiction",
    copy: "The essential titles from the last two decades.",
    description:
      "A shelf of the novels published since 2000 that will define the century's African letters.",
    curator: "Kofi Mensah",
    image: "/images/list-fiction.jpg",
    imageAlt: "Person reading a book",
    bookIds: [
      "half-of-a-yellow-sun",
      "americanah",
      "kintu",
      "homegoing",
      "afterlives",
      "dust",
      "purple-hibiscus",
      "dragonfly-sea",
    ],
  },
  {
    id: "essential-kenyan-literature",
    slug: "essential-kenyan-literature",
    title: "Essential Kenyan Literature",
    copy: "The stories that shaped a nation's letters.",
    description:
      "From Ngũgĩ to Owuor, the essential Kenyan books that every reader should know.",
    curator: "Amina Yusuf",
    image: "/images/list-kenya.jpg",
    imageAlt: "A person browsing shelves in a library",
    bookIds: [
      "grain-of-wheat",
      "weep-not-child",
      "petals-of-blood",
      "river-between",
      "dust",
      "dragonfly-sea",
      "one-day-i-will-write",
    ],
  },
  {
    id: "starting-something-new",
    slug: "books-for-starting-something-new",
    title: "Books for Starting Something New",
    copy: "For the ambitious, the restless and the about-to-begin.",
    description:
      "Practical and inspiring reads for the season of beginnings, whether a business, a habit or a life.",
    curator: "Daniel Otieno",
    image: "/images/list-starting.jpg",
    imageAlt: "A book with reading glasses on top",
    bookIds: [
      "atomic-habits",
      "start-with-why",
      "the-alchemist",
      "long-walk-to-freedom",
      "mans-search-for-meaning",
      "one-day-i-will-write",
    ],
  },
  {
    id: "books-about-becoming",
    slug: "books-about-becoming",
    title: "Books About Becoming",
    copy: "On growth, identity and the people we are still becoming.",
    description:
      "A reflective list about the long, quiet work of becoming yourself.",
    curator: "Nadia Okonkwo",
    image: "/images/art-becoming.jpg",
    imageAlt: "Book with a cup of coffee",
    bookIds: [
      "born-a-crime",
      "purple-hibiscus",
      "americanah",
      "the-wretched-of-the-earth",
      "the-prophet",
    ],
  },
];

export const getReadingListBySlug = (slug: string) =>
  readingLists.find((r) => r.slug === slug);

/* ------------------------------------------------------------------ */
/* Authors                                                             */
/* ------------------------------------------------------------------ */

export const authors: Author[] = [
  {
    id: "ngugi-wa-thiongo",
    slug: "ngugi-wa-thiongo",
    name: "Ngũgĩ wa Thiong'o",
    role: "Novelist · Playwright · Essayist",
    image: "/images/author-ngugi.jpg",
    imageAlt: "Portrait of Ngũgĩ wa Thiong'o",
    note: "Author of A Grain of Wheat & Decolonising the Mind",
    bio: "Ngũgĩ wa Thiong'o is one of Africa's most important writers. Born in Limuru, Kenya, in 1938, he has written novels, plays and essays in Gikuyu and English, and has argued for fifty years that African languages must carry African literature. His memoir-in-prison, Detained, and the novel Wizard of the Crow are landmarks.",
    location: "Limuru, Kenya",
    genres: ["Fiction", "Essays", "Playwriting"],
  },
  {
    id: "yvonne-adhiambo-owuor",
    slug: "yvonne-adhiambo-owuor",
    name: "Yvonne Adhiambo Owuor",
    role: "Novelist · Short Story Writer",
    image: "/images/author-owuor.jpg",
    imageAlt: "Portrait of Yvonne Adhiambo Owuor",
    note: "Author of Dust & The Dragonfly Sea",
    bio: "Yvonne Adhiambo Owuor grew up in Nairobi and won the Caine Prize for her story Weight of Whispers. Her novels Dust and The Dragonfly Sea have established her as the great prose stylist of contemporary Kenyan fiction, writing with a lyrical intensity that stays with the reader.",
    location: "Nairobi, Kenya",
    genres: ["Fiction", "Short Stories"],
  },
  {
    id: "mukoma-wa-ngugi",
    slug: "mukoma-wa-ngugi",
    name: "Mũkoma wa Ngũgĩ",
    role: "Novelist · Poet · Critic",
    image: "/images/author-mukoma.jpg",
    imageAlt: "Portrait of Mũkoma wa Ngũgĩ",
    note: "Author of Mrs. Shaw & Nairobi Heat",
    bio: "Mũkoma wa Ngũgĩ is a Kenyan-American writer, poet and critic, and the son of Ngũgĩ wa Thiong'o. He is the author of the crime novel Nairobi Heat and the verse novel Mrs. Shaw, and he co-founded the Jalada collective, a pan-African literary platform.",
    location: "Ithaca, New York",
    genres: ["Fiction", "Poetry", "Criticism"],
  },
  {
    id: "binyavanga-wainaina",
    slug: "binyavanga-wainaina",
    name: "Binyavanga Wainaina",
    role: "Memoirist · Essayist · Editor",
    image: "/images/author-wainaina.jpg",
    imageAlt: "Portrait of Binyavanga Wainaina",
    note: "Author of One Day I Will Write About This Place",
    bio: "Binyavanga Wainaina (1971-2019) was a Kenyan writer, editor and cultural provocateur. He founded the literary magazine Kwani?, won the Caine Prize, and wrote the landmark memoir One Day I Will Write About This Place. His essay How to Write About Africa remains the sharpest satire in African letters.",
    location: "Nairobi, Kenya",
    genres: ["Memoir", "Essays", "Journalism"],
  },
  {
    id: "ayi-kwei-armah",
    slug: "ayi-kwei-armah",
    name: "Ayi Kwei Armah",
    role: "Novelist · Essayist",
    image: "",
    imageAlt: "Portrait placeholder for Ayi Kwei Armah",
    note: "Author of The Beautyful Ones Are Not Yet Born",
    bio: "Ayi Kwei Armah, born in 1939 in Sekondi-Takoradi, Ghana, is one of the great novelists of postcolonial Africa. The Beautyful Ones Are Not Yet Born announced a writer of ferocious moral clarity, and his later novels explore African history with philosophical ambition.",
    location: "Accra, Ghana",
    genres: ["Fiction", "Essays"],
  },
  {
    id: "jennifer-nansubuga-makumbi",
    slug: "jennifer-nansubuga-makumbi",
    name: "Jennifer Nansubuga Makumbi",
    role: "Novelist · Short Story Writer",
    image: "",
    imageAlt: "Portrait placeholder for Jennifer Nansubuga Makumbi",
    note: "Author of Kintu",
    bio: "Jennifer Nansubuga Makumbi is a Ugandan novelist and short story writer. Kintu, her reimagining of Ugandan history through the story of one cursed clan, was published to wide acclaim and is now regarded as a modern classic of African fiction.",
    location: "Kampala, Uganda",
    genres: ["Fiction", "Short Stories"],
  },
  {
    id: "chinua-achebe",
    slug: "chinua-achebe",
    name: "Chinua Achebe",
    role: "Novelist · Poet · Critic",
    image: "",
    imageAlt: "Portrait placeholder for Chinua Achebe",
    note: "Author of Things Fall Apart",
    bio: "Chinua Achebe (1930-2013) is the founding father of modern African literature. Things Fall Apart, published in 1958, told the story of colonialism from the other side and changed the world's literary map. His essays and lectures made him the continent's foremost literary conscience.",
    location: "Ogidi, Nigeria",
    genres: ["Fiction", "Essays", "Poetry"],
  },
  {
    id: "chimamanda-ngozi-adichie",
    slug: "chimamanda-ngozi-adichie",
    name: "Chimamanda Ngozi Adichie",
    role: "Novelist · Essayist",
    image: "",
    imageAlt: "Portrait placeholder for Chimamanda Ngozi Adichie",
    note: "Author of Half of a Yellow Sun & Americanah",
    bio: "Chimamanda Ngozi Adichie, born in 1977 in Enugu, Nigeria, is one of the most widely read writers in the world. Her novels, stories and essays, including the TED talk that became We Should All Be Feminists, have made her a defining voice of her generation.",
    location: "Abuja, Nigeria",
    genres: ["Fiction", "Essays"],
  },
  {
    id: "yaa-gyasi",
    slug: "yaa-gyasi",
    name: "Yaa Gyasi",
    role: "Novelist",
    image: "",
    imageAlt: "Portrait placeholder for Yaa Gyasi",
    note: "Author of Homegoing",
    bio: "Yaa Gyasi was born in Ghana and raised in Alabama. Her debut novel Homegoing, which traces the descendants of two sisters across three centuries, was published in 2016 to international acclaim and established her as a major new voice.",
    location: "Brooklyn, New York",
    genres: ["Fiction"],
  },
  {
    id: "abdulrazak-gurnah",
    slug: "abdulrazak-gurnah",
    name: "Abdulrazak Gurnah",
    role: "Novelist",
    image: "",
    imageAlt: "Portrait placeholder for Abdulrazak Gurnah",
    note: "Author of Paradise & Afterlives",
    bio: "Abdulrazak Gurnah was born in Zanzibar in 1948 and has written about the East African coast, displacement and the afterlife of empire for four decades. He won the Nobel Prize in Literature in 2021.",
    location: "Canterbury, England",
    genres: ["Fiction"],
  },
  {
    id: "okot-pbitek",
    slug: "okot-pbitek",
    name: "Okot p'Bitek",
    role: "Poet · Anthropologist",
    image: "",
    imageAlt: "Portrait placeholder for Okot p'Bitek",
    note: "Author of Song of Lawino",
    bio: "Okot p'Bitek (1931-1982) was a Ugandan poet, anthropologist and teacher. Song of Lawino, written in Acholi and published in English in 1966, is one of the most important poems in African literature.",
    location: "Gulu, Uganda",
    genres: ["Poetry", "Anthropology"],
  },
  {
    id: "trevor-noah",
    slug: "trevor-noah",
    name: "Trevor Noah",
    role: "Comedian · Memoirist",
    image: "",
    imageAlt: "Portrait placeholder for Trevor Noah",
    note: "Author of Born a Crime",
    bio: "Trevor Noah was born in Johannesburg in 1984. Born a Crime, his memoir of growing up under apartheid and after it, became an international bestseller and was praised for its humour, honesty and portrait of his remarkable mother.",
    location: "Johannesburg, South Africa",
    genres: ["Memoir", "Humor"],
  },
  {
    id: "nelson-mandela",
    slug: "nelson-mandela",
    name: "Nelson Mandela",
    role: "Statesman · Memoirist",
    image: "",
    imageAlt: "Portrait placeholder for Nelson Mandela",
    note: "Author of Long Walk to Freedom",
    bio: "Nelson Mandela (1918-2013) led the struggle against apartheid and became the first democratically elected president of South Africa. Long Walk to Freedom, his autobiography, is among the most important political memoirs ever written.",
    location: "Mvezo, South Africa",
    genres: ["Memoir", "Politics", "History"],
  },
  {
    id: "marcus-aurelius",
    slug: "marcus-aurelius",
    name: "Marcus Aurelius",
    role: "Philosopher · Emperor",
    image: "",
    imageAlt: "Portrait placeholder for Marcus Aurelius",
    note: "Author of Meditations",
    bio: "Marcus Aurelius (121-180) ruled Rome as emperor and wrote Meditations in the field, as a private notebook of self-command. It survives as the most direct book of Stoic philosophy ever written.",
    location: "Rome, Roman Empire",
    genres: ["Philosophy"],
  },
  {
    id: "viktor-frankl",
    slug: "viktor-frankl",
    name: "Viktor E. Frankl",
    role: "Psychiatrist · Philosopher",
    image: "",
    imageAlt: "Portrait placeholder for Viktor E. Frankl",
    note: "Author of Man's Search for Meaning",
    bio: "Viktor E. Frankl (1905-1997) was an Austrian psychiatrist and a survivor of the Nazi camps. Man's Search for Meaning, his account of how meaning keeps a person alive, has sold more than ten million copies.",
    location: "Vienna, Austria",
    genres: ["Philosophy", "Psychology"],
  },
  {
    id: "james-clear",
    slug: "james-clear",
    name: "James Clear",
    role: "Author · Researcher",
    image: "",
    imageAlt: "Portrait placeholder for James Clear",
    note: "Author of Atomic Habits",
    bio: "James Clear writes about habits, decision-making and continuous improvement. Atomic Habits, his 2018 synthesis of behavioural research into a practical system, has become one of the best-selling nonfiction books of the century.",
    location: "Columbus, Ohio",
    genres: ["Personal Development", "Behavioral Science"],
  },
  {
    id: "simon-sinek",
    slug: "simon-sinek",
    name: "Simon Sinek",
    role: "Author · Speaker",
    image: "",
    imageAlt: "Portrait placeholder for Simon Sinek",
    note: "Author of Start with Why",
    bio: "Simon Sinek studies how leaders inspire action. His idea that great leaders start with why rather than what or how has influenced teams and organisations around the world.",
    location: "London, England",
    genres: ["Leadership", "Business"],
  },
  {
    id: "adam-hochschild",
    slug: "adam-hochschild",
    name: "Adam Hochschild",
    role: "Historian · Journalist",
    image: "",
    imageAlt: "Portrait placeholder for Adam Hochschild",
    note: "Author of King Leopold's Ghost",
    bio: "Adam Hochschild is an American historian and journalist. King Leopold's Ghost, his account of the Congo's plunder and the first great human rights movement, is a masterpiece of narrative history.",
    location: "San Francisco, California",
    genres: ["History", "Journalism"],
  },
  {
    id: "kahlil-gibran",
    slug: "kahlil-gibran",
    name: "Kahlil Gibran",
    role: "Poet · Philosopher",
    image: "",
    imageAlt: "Portrait placeholder for Kahlil Gibran",
    note: "Author of The Prophet",
    bio: "Kahlil Gibran (1883-1931) was a Lebanese-American poet and painter. The Prophet, his book of prose poems on love, work and sorrow, is one of the most translated books of all time.",
    location: "Bsharri, Lebanon",
    genres: ["Poetry", "Spirituality"],
  },
  {
    id: "frantz-fanon",
    slug: "frantz-fanon",
    name: "Frantz Fanon",
    role: "Psychiatrist · Philosopher · Revolutionary",
    image: "",
    imageAlt: "Portrait placeholder for Frantz Fanon",
    note: "Author of The Wretched of the Earth",
    bio: "Frantz Fanon (1925-1961) was a psychiatrist and political philosopher from Martinique. The Wretched of the Earth, written at the end of his short life, became a defining text of decolonisation worldwide.",
    location: "Fort-de-France, Martinique",
    genres: ["Philosophy", "Politics"],
  },
  {
    id: "paulo-coelho",
    slug: "paulo-coelho",
    name: "Paulo Coelho",
    role: "Novelist",
    image: "",
    imageAlt: "Portrait placeholder for Paulo Coelho",
    note: "Author of The Alchemist",
    bio: "Paulo Coelho, born in 1947 in Rio de Janeiro, is one of the best-selling writers in the world. The Alchemist, his fable about following one's personal legend, has been translated into more than eighty languages.",
    location: "Rio de Janeiro, Brazil",
    genres: ["Fiction", "Spirituality"],
  },
  {
    id: "ifeoma-onyefulu",
    slug: "ifeoma-onyefulu",
    name: "Ifeoma Onyefulu",
    role: "Writer · Photographer",
    image: "",
    imageAlt: "Portrait placeholder for Ifeoma Onyefulu",
    note: "Author of A Is for Africa",
    bio: "Ifeoma Onyefulu is a Nigerian author and photographer whose children's books open windows onto African village life for young readers around the world.",
    location: "Enugu, Nigeria",
    genres: ["Children's Books", "Photography"],
  },
  {
    id: "jeanette-winter",
    slug: "jeanette-winter",
    name: "Jeanette Winter",
    role: "Illustrator · Children's Author",
    image: "",
    imageAlt: "Portrait placeholder for Jeanette Winter",
    note: "Author of Wangari's Trees of Peace",
    bio: "Jeanette Winter is an American author and illustrator known for picture-book biographies of extraordinary people, including Wangari Maathai, Frida Kahlo and Mahatma Gandhi.",
    location: "New York, New York",
    genres: ["Children's Books", "Illustration"],
  },
];

export const getAuthorBySlug = (slug: string) =>
  authors.find((a) => a.slug === slug);

export const articlesByAuthor = (authorSlug: string) =>
  articles.filter((a) => a.authorSlug === authorSlug);

export const relatedAuthorsByBook = (book: Book) => {
  const sameAuthor = getAuthorBySlug(book.authorSlug);
  const sameCategory = books
    .filter(
      (b) => b.id !== book.id && b.categorySlugs.some((c) => book.categorySlugs.includes(c)),
    )
    .slice(0, 4)
    .map((b) => getAuthorBySlug(b.authorSlug))
    .filter((a): a is Author => Boolean(a));
  const merged = sameAuthor ? [sameAuthor, ...sameCategory] : sameCategory;
  return merged.filter((a, i, arr) => arr.findIndex((x) => x.slug === a.slug) === i).slice(0, 4);
};

/* ------------------------------------------------------------------ */
/* Articles / Journal                                                  */
/* ------------------------------------------------------------------ */

export const articles: Article[] = [
  {
    id: "why-we-still-need-books",
    slug: "why-we-still-need-books",
    category: "Essays",
    title: "Why We Still Need Books in a Digital World",
    subtitle: "The book is not a dying format. It is a resistance movement.",
    excerpt:
      "In an age of endless scroll, the book remains a rare place where attention is given freely and completely.",
    author: "Amina Yusuf",
    date: "12 Aug 2026",
    readTime: "8 min read",
    image: "/images/art-need-books.jpg",
    imageAlt: "Person reading a book beside a plant",
    popular: true,
    content: [
      { type: "p", text: "Every few years the same headline arrives: the book is dying, attention is dead, nobody reads anymore. And every few years the same quiet fact survives the headline. People still read. They read on trains, in hospital waiting rooms, at kitchen tables long after everyone else has gone to bed." },
      { type: "p", text: "What has changed is not reading itself but the pressure we feel around it. The phone demands nothing less than all of us, and it has designed itself so that our attention is the product it sells. A book asks for something different. It asks for a beginning, a middle and an end, and for the patience to live in someone else's sentences for a while." },
      { type: "h2", text: "Attention as a gift" },
      { type: "p", text: "To read a book in 2026 is to give your attention away on purpose, to a stranger who will never know who you are. That is a strange and beautiful thing. The novelist asks you to believe in people who do not exist, and you do, because the act of belief is the act of reading." },
      { type: "quote", text: "A book is the only place where your attention can still be spent and not spent, given and kept, at the same time." },
      { type: "p", text: "We do not need books to be faster. We need them to be what they have always been: the slow technology that lets a thought settle. The scroll moves past a thought; the page lets it stay." },
      { type: "h2", text: "The library as a quiet room" },
      { type: "p", text: "There is a reason the library is the one public room where silence is still welcome. It is not nostalgia. It is a model for a kind of attention the world still needs: collective, unforced, and unmeasured." },
      { type: "p", text: "The book will outlast the platforms because it does not need to be refreshed. It does not chase trends. It waits for the reader to arrive, and the reader always does, usually a little changed, usually grateful." },
    ],
    relatedBookIds: ["kintu", "decolonising-the-mind", "mans-search-for-meaning"],
  },
  {
    id: "reading-as-a-way-of-becoming",
    slug: "reading-as-a-way-of-becoming",
    category: "Essays",
    title: "Reading as a Way of Becoming",
    subtitle: "Every book we choose is a small decision about who we are becoming next.",
    excerpt:
      "Every book we choose is a small decision about who we are becoming next. Why reading is self-making.",
    author: "Wanjiru Kamau",
    date: "5 Aug 2026",
    readTime: "9 min read",
    image: "/images/art-becoming.jpg",
    imageAlt: "Book with a cup of coffee",
    popular: true,
    content: [
      { type: "p", text: "You can tell a great deal about a person from the books they choose and, just as honestly, from the books they never finish. The bookshelf is a portrait of the self, painted over time, corrected in pencil, never quite finished." },
      { type: "p", text: "This is why we say a book found us at the right time. It did not. We became the kind of person who could meet it, and then it arrived, and the meeting changed us a little more. Reading is not passive. It is the slowest form of becoming." },
      { type: "h2", text: "The company of sentences" },
      { type: "p", text: "We read to be formed by other minds. The writer on the page is not a friend, exactly, but is something older: a voice that stays in the room after you have closed the book, shaping how you describe your own day, your own losses, your own loves." },
      { type: "quote", text: "A book is a mirror you have to turn around to see yourself in." },
      { type: "p", text: "The books we read in difficult years tend to be the ones we keep. They become landmarks. We say to ourselves, I read that when, and the sentence completes itself with the season, the room, the weather, the person we no longer are." },
      { type: "h2", text: "A practice, not a habit" },
      { type: "p", text: "Habits repeat. Practices change you. Reading is closer to a practice: you return to it not because it is easy but because it is clarifying. It is how we rehearse being someone we have not yet become." },
      { type: "p", text: "So choose the next book as if it mattered, because it does. You are not simply filling an evening. You are deciding, page by page, who the next version of you will be." },
    ],
    relatedBookIds: ["the-alchemist", "one-day-i-will-write", "born-a-crime"],
  },
  {
    id: "what-makes-a-book-stay",
    slug: "what-makes-a-book-stay",
    category: "Book Reviews",
    title: "What Makes a Book Stay With Us?",
    subtitle: "Some books are read and forgotten. Others become part of the way we see.",
    excerpt:
      "Some books are read and forgotten. Others become part of the way we see. A meditation on staying power.",
    author: "Nadia Okonkwo",
    date: "28 Jul 2026",
    readTime: "6 min read",
    image: "/images/art-stay-with-us.jpg",
    imageAlt: "Open book resting on a wooden table",
    popular: false,
    content: [
      { type: "p", text: "There are books you finish and admire, and books you finish and cannot leave. The first kind earns respect. The second kind changes the furniture of your mind. What is the difference?" },
      { type: "p", text: "It is rarely the plot. The books that stay with us are often the ones we could not summarise without embarrassment, because their power is not in what happens but in what the writing makes us feel while it happens." },
      { type: "h2", text: "The work of a sentence" },
      { type: "p", text: "A sentence can stay with you for decades. It becomes a private language, a way of naming something that had no name before. That is the quiet engineering of staying power: the writer gives us words for what we already knew but could not say." },
      { type: "quote", text: "The best books do not end. They are merely interrupted by their final page." },
      { type: "p", text: "We also keep books that met us at a turning point. The book is not only itself; it is the person we were when we read it. To reread it is to visit that person, and to measure the distance travelled." },
      { type: "h2", text: "Why we reread" },
      { type: "p", text: "We reread not to learn the story but to witness it change. The pages are the same; we are not. That is the deepest test of a book: whether it can be different every time we open it, because we are different every time we arrive." },
    ],
    relatedBookIds: ["grain-of-wheat", "petals-of-blood", "the-prophet"],
  },
  {
    id: "new-generation-of-african-writers",
    slug: "new-generation-of-african-writers",
    category: "Authors",
    title: "The New Generation of African Writers",
    subtitle: "A portrait of the young voices reimagining the continent's stories.",
    excerpt:
      "A portrait of the young voices reimagining the continent's stories for a global readership.",
    author: "Kofi Mensah",
    authorSlug: "kofi-mensah",
    date: "20 Jul 2026",
    readTime: "12 min read",
    image: "/images/art-new-writers.jpg",
    imageAlt: "Woman reading intently",
    popular: true,
    content: [
      { type: "p", text: "A generation ago, the question asked of an African writer was usually about authenticity: was this writing really African? The question betrayed the anxiety behind it, and it has largely disappeared. Nobody asks Yaa Gyasi whether Homegoing is authentically Ghanaian, or Makumbi whether Kintu is authentically Ugandan. The books are too good for the question." },
      { type: "p", text: "The new generation writes in the full confidence that the continent is a subject, not a genre. They move between Lagos and London, Accra and the American South, without apology, because the stories demand it." },
      { type: "h2", text: "The archive of the ordinary" },
      { type: "p", text: "What distinguishes this generation is its interest in ordinary life. The grand themes are still there, empire and exile and inheritance, but they are told through kitchens, buses, market stalls and the long work of family. The epic has learned to speak softly." },
      { type: "quote", text: "The new writers are not explaining Africa. They are simply writing, and the world is finally listening." },
      { type: "h2", text: "Publishing from the continent" },
      { type: "p", text: "Just as important is where these books are born. Journals like Kwani?, publishers like Transit Books, and the growth of literary festivals across Nairobi, Lagos and Accra mean the conversation no longer needs a detour through the old capitals of publishing. The centre of African letters is Africa." },
      { type: "p", text: "What we are watching is not a wave but a widening. The writers below are a small map of where African fiction is going, and the books on our shelves are the proof that it has already arrived." },
    ],
    relatedBookIds: ["homegoing", "kintu", "afterlives", "americanah"],
  },
  {
    id: "how-kenya-reads",
    slug: "how-kenya-reads",
    category: "Kenyan Stories",
    title: "How Kenya Reads: Notes on a Reading Nation",
    subtitle: "From matatu libraries to living room bookshelves, Kenya is a country of readers.",
    excerpt:
      "A field report from the bookshops, street libraries and reading rooms of modern Kenya.",
    author: "Wanjiru Kamau",
    date: "10 Jul 2026",
    readTime: "7 min read",
    image: "/images/list-kenya.jpg",
    imageAlt: "A person browsing shelves in a library",
    popular: false,
    content: [
      { type: "p", text: "Ask a Kenyan bookseller where the readers are and you will not get a simple answer. They are in the malls, in the corner bookshops that have outlasted every change of regime, in the secondhand stalls along Moi Avenue where a paperback costs less than a chapati." },
      { type: "p", text: "Reading in Kenya has never been a single activity. It is the schoolboy with a set book under his arm, the professional downloading audiobooks before a flight to London, the matatu driver who keeps a battered novel wedged behind his seat for the traffic." },
      { type: "h2", text: "The set book generation" },
      { type: "p", text: "Much of Kenya's literary culture begins in the classroom. Generations met Ngũgĩ and Meja Mwangi through set books, and many readers trace the whole habit back to a single title encountered in Form Three. The syllabus has often been controversial, but it has never failed to make readers." },
      { type: "quote", text: "In Kenya you do not choose to meet the classics. They arrive in your school bag and change you anyway." },
      { type: "h2", text: "A market finding its shape" },
      { type: "p", text: "What has changed in the last twenty years is the confidence of the local market. Kenyan publishers, literary festivals and a generation of homegrown bestsellers mean that a reader in Nairobi no longer needs to wait for London to tell them what to read next." },
      { type: "p", text: "The result is a country where the question is not whether people read, but what they are reading, and where, and why. These are the questions a bookstore exists to ask." },
    ],
    relatedBookIds: ["one-day-i-will-write", "grain-of-wheat", "dust"],
  },
  {
    id: "rereading-grain-of-wheat",
    slug: "rereading-a-grain-of-wheat",
    category: "Book Reviews",
    title: "Re-reading A Grain of Wheat, Fifty Years Later",
    subtitle: "Ngũgĩ's novel of the eve of independence still reads like a letter from the future.",
    excerpt:
      "The questions Ngũgĩ asked in 1967, about freedom and its costs, have not gone away.",
    author: "Nadia Okonkwo",
    date: "1 Jul 2026",
    readTime: "8 min read",
    image: "/images/art-stay-with-us.jpg",
    imageAlt: "Open book resting on a wooden table",
    popular: false,
    content: [
      { type: "p", text: "To reread A Grain of Wheat is to be reminded how unusual it is for a novel about a nation's founding to be written with such suspicion of the story it tells itself. Ngũgĩ writes on the eve of independence, and the mood is not triumph. It is accounting." },
      { type: "p", text: "The village of Thabai is preparing to celebrate, and everyone in it is preparing to remember themselves a certain way. The novel's quiet genius is to watch the remembering fail." },
      { type: "h2", text: "The silence at the centre" },
      { type: "p", text: "Mugo, the reticent hero, carries a secret the novel holds back with great patience. The structure of the book is the structure of memory: events circle, return, and refuse to settle. Betrayal is not a plot twist here. It is the weather." },
      { type: "quote", text: "The novel asks what freedom is worth, and how it is paid for, and who pays it first." },
      { type: "p", text: "Fifty years later the book has not dated into history. The questions, about who gets to tell the nation's story and what is hidden beneath the official version, are the questions of every country that has ever celebrated a revolution and then looked around at the room." },
      { type: "p", text: "Re-reading it, what strikes you is not the strangeness of the past but its familiarity. Ngũgĩ was writing about his moment; he has written about ours." },
    ],
    relatedBookIds: ["grain-of-wheat", "petals-of-blood", "weep-not-child"],
  },
  {
    id: "bookshelf-we-carry",
    slug: "the-bookshelf-we-carry",
    category: "Ideas",
    title: "The Bookshelf We Carry: On Diaspora and Home",
    subtitle: "For the reader who lives between two places, books become the portable homeland.",
    excerpt:
      "For the reader who lives between two places, the bookshelf becomes a portable homeland.",
    author: "Kofi Mensah",
    date: "22 Jun 2026",
    readTime: "10 min read",
    image: "/images/col-think.jpg",
    imageAlt: "Quiet library reading room",
    popular: true,
    content: [
      { type: "p", text: "There is a particular loneliness to reading in a language away from the place that speaks it, and a particular comfort in the book that knows where you are from. For the diaspora reader, literature does double work. It explains the place you are in, and it keeps the place you left." },
      { type: "p", text: "The bookshelf of the diaspora is a different kind of archive. It is not arranged for display. It is arranged for retrieval: the book you need to explain your grandfather, the novel that names the food, the memoir that describes the compound you remember from only two visits." },
      { type: "h2", text: "Writing between places" },
      { type: "p", text: "So many of the books we sell at Man Within are written between places, and this is not a weakness. Adichie wrote Americanah between Nigeria and America. Gyasi wrote Homegoing between Ghana and the stories her family carried. The in-between is not empty. It is a country with its own literature." },
      { type: "quote", text: "Home is not a place you leave. It is a set of books you can carry." },
      { type: "p", text: "We built this bookstore with that reader in mind: the one who is based in Nairobi and lives everywhere, who sends a book home as a gift and reads another on the flight out. For that reader, a bookstore is not a shop. It is the room where both halves of the life are allowed in." },
    ],
    relatedBookIds: ["americanah", "homegoing", "dragonfly-sea"],
  },
  {
    id: "library-in-exile",
    slug: "the-library-in-exile",
    category: "Ideas",
    title: "Reading as Resistance: A Library in Exile",
    subtitle: "When a writer writes in secret, the book becomes a form of defiance.",
    excerpt:
      "When a writer writes in secret, the book becomes a form of defiance.",
    author: "Amina Yusuf",
    date: "14 Jun 2026",
    readTime: "9 min read",
    image: "/images/cat-history.jpg",
    imageAlt: "Tall library shelves",
    popular: false,
    content: [
      { type: "p", text: "Devil on the Cross was written on toilet paper in a Kenyan prison cell. Ngũgĩ smuggled it out a few pages at a time, and the novel was published while its author was still detained. It is hard to think of a more literal proof that a story can survive its writer's captivity." },
      { type: "p", text: "Reading, too, has always been an act that regimes fear. Dictators ban books not because they are flimsy but because they are durable. A book does not need a signal. It does not need permission. It waits." },
      { type: "h2", text: "The book that outlives the ban" },
      { type: "p", text: "Across the history of African literature, the pattern repeats: the writer silenced, the book smuggled, the generation that finally reads it openly. The text is the last word, and the last word is always the writer's." },
      { type: "quote", text: "You can arrest the writer. You cannot arrest the reader who remembers." },
      { type: "p", text: "A library is not a warehouse of neutral objects. It is a memory kept against the officials of forgetting. To build a bookstore is to take a side in a very old argument about who gets to decide what is remembered." },
      { type: "p", text: "We think about that argument every day, and we are glad to be on the side of the readers." },
    ],
    relatedBookIds: ["devil-on-the-cross", "the-wretched-of-the-earth", "wizard-of-the-crow"],
  },
  {
    id: "in-conversation-mukoma",
    slug: "in-conversation-mukoma-wa-ngugi",
    category: "Authors",
    title: "In Conversation: Mũkoma wa Ngũgĩ",
    subtitle: "On crime fiction, verse novels and the Jalada collective.",
    excerpt:
      "Mũkoma wa Ngũgĩ on crime fiction, verse novels and building a pan-African literary platform.",
    author: "Man Within Editorial",
    date: "2 Jun 2026",
    readTime: "11 min read",
    image: "/images/art-new-writers.jpg",
    imageAlt: "Woman reading intently",
    popular: false,
    content: [
      { type: "p", text: "Man Within: Nairobi Heat begins in Wisconsin and ends in Kibera. Why a crime novel, and why Nairobi?" },
      { type: "p", text: "Mũkoma wa Ngũgĩ: Crime fiction is a way of asking how a society treats its citizens, which is the most political question there is. And Nairobi has always been a city that runs on a certain kind of nervous energy. It suited the form." },
      { type: "h2", text: "The verse novel as a challenge" },
      { type: "p", text: "MW: Mrs. Shaw is a novel written entirely in verse. What made you attempt that?" },
      { type: "p", text: "MwN: I wanted the reader to feel the compression of exile, which is a life lived at a low hum of not quite belonging. Verse does that. It makes every word accountable." },
      { type: "quote", text: "Exile is not a place. It is a register. You can hear it in how a person speaks about home." },
      { type: "h2", text: "Building Jalada" },
      { type: "p", text: "MW: You helped found the Jalada collective. What was the idea?" },
      { type: "p", text: "MwN: To build a platform where African writers could publish without waiting to be discovered. The anthology was just the beginning. We wanted infrastructure, and we wanted it pan-African." },
      { type: "p", text: "The conversation ran long and went everywhere, from Ngũgĩ senior's example to the future of the African novel. The short version: the next classic is probably being drafted in a Nairobi coffee shop right now, and we will publish it gladly." },
    ],
    relatedBookIds: ["nairobi-heat", "mrs-shaw", "wizard-of-the-crow"],
  },
  {
    id: "five-essays-to-start",
    slug: "five-essays-to-start-your-year",
    category: "Reading Lists",
    title: "Five Essays to Start Your Year",
    subtitle: "Short, sharp pieces that set the tone for the reading year ahead.",
    excerpt:
      "Five short, sharp essays to set the tone for your reading year.",
    author: "Wanjiru Kamau",
    date: "28 May 2026",
    readTime: "5 min read",
    image: "/images/art-becoming.jpg",
    imageAlt: "Book with a cup of coffee",
    popular: false,
    content: [
      { type: "p", text: "Some reading years deserve to begin slowly. Start with the essay, the form built for a single sustained idea, and let five of them set the pace." },
      { type: "p", text: "The essay is the most forgiving form in literature. It can begin anywhere, ramble honestly, and still arrive somewhere true. For a reader easing back into the habit, there is no better door." },
      { type: "h2", text: "The five" },
      { type: "p", text: "We asked our booksellers for the essays that reset their own reading each January, and we kept the five that kept coming back: Decolonising the Mind for its argument, We Should All Be Feminists for its clarity, Meditations for its calm, and two essays from One Day I Will Write About This Place for their laughter." },
      { type: "quote", text: "Start with what is short and true. The long books will wait for you." },
      { type: "p", text: "The essays are all on the shelf behind you, all under a hundred pages, all certain to be finished before the month is. A small beginning, but beginnings are the point." },
    ],
    relatedBookIds: ["decolonising-the-mind", "we-should-all-be-feminists", "meditations", "one-day-i-will-write"],
  },
];

export const getArticleBySlug = (slug: string) =>
  articles.find((a) => a.slug === slug);

export const journalCategories = [
  "All",
  "Essays",
  "Book Reviews",
  "Culture",
  "Ideas",
  "Authors",
  "Reading Lists",
  "Kenyan Stories",
];

/* ------------------------------------------------------------------ */
/* FAQ                                                                 */
/* ------------------------------------------------------------------ */

export const faqs: Faq[] = [
  {
    category: "Orders",
    items: [
      { q: "How do I place an order?", a: "Browse the bookstore, add the books you want to your bag, and proceed to checkout. You can pay with M-Pesa, card or bank transfer." },
      { q: "Can I change or cancel my order?", a: "Yes, as long as the order has not been dispatched. Contact us within 24 hours of ordering and we will make the change or issue a full refund." },
      { q: "Will I get a receipt?", a: "A receipt is emailed to you the moment your order is confirmed, and a second copy is sent when your books are dispatched." },
    ],
  },
  {
    category: "Shipping",
    items: [
      { q: "How long does delivery take in Nairobi?", a: "Orders in Nairobi are delivered within 1 to 3 working days. Same-day delivery is available for orders placed before 1pm in select areas." },
      { q: "Do you deliver outside Nairobi?", a: "Yes. We deliver to all 47 counties through partner couriers, typically within 3 to 6 working days." },
      { q: "How much does shipping cost?", a: "Shipping within Kenya is KES 300 for orders under KES 3,000 and free for orders above it. International shipping is calculated at checkout." },
    ],
  },
  {
    category: "Returns",
    items: [
      { q: "What is your return policy?", a: "Books can be returned within 14 days of delivery if they are damaged, defective or the wrong title. We also offer a 7 day change of mind window on unopened books." },
      { q: "How do I start a return?", a: "Email us with your order number and a photo of the book. We will arrange a pickup or a drop-off point and process your refund within 3 working days." },
    ],
  },
  {
    category: "Payments",
    items: [
      { q: "Which payment methods do you accept?", a: "We accept M-Pesa, Visa and Mastercard, and direct bank transfer for larger orders. International card payments are handled securely at checkout." },
      { q: "Is it safe to pay online?", a: "Yes. Payments are processed through trusted gateways with encryption. We never see or store your full card details." },
    ],
  },
  {
    category: "Books",
    items: [
      { q: "Are the books you sell new?", a: "All books on the site are new, purchased from publishers and authorised distributors. Where a title is available secondhand, we say so clearly." },
      { q: "Do you sell ebooks?", a: "Not yet. We believe in the physical book, but audiobooks are on our roadmap and we will announce them in the journal first." },
      { q: "Can you order a book you do not stock?", a: "Yes. If a title is in print, we can usually source it. Send us the details and we will quote you a price and a timeline." },
    ],
  },
  {
    category: "International Orders",
    items: [
      { q: "Do you ship internationally?", a: "Yes. We ship to most countries through international couriers. Rates and delivery times are calculated at checkout." },
      { q: "Are international orders tracked?", a: "Every international order is fully tracked, and you will receive the tracking number by email once your parcel leaves Nairobi." },
      { q: "Will I have to pay customs duties?", a: "Customs duties and import taxes are the responsibility of the buyer and vary by country. We include clear guidance at checkout." },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Navigation                                                          */
/* ------------------------------------------------------------------ */

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Books", href: "/books" },
  { label: "Categories", href: "/categories" },
  { label: "Journal", href: "/journal" },
  { label: "Authors", href: "/authors" },
  { label: "Collections", href: "/collections" },
  { label: "About", href: "/about" },
];

export const adminNav = [
  { label: "Dashboard", href: "/admin" },
  { label: "Books", href: "/admin/books" },
  { label: "Authors", href: "/admin/authors" },
  { label: "Articles", href: "/admin/articles" },
  { label: "Media", href: "/admin/media" },
  { label: "Orders", href: "/admin#orders" },
  { label: "Customers", href: "/admin#customers" },
  { label: "Collections", href: "/admin#collections" },
  { label: "Reading Lists", href: "/admin#reading-lists" },
  { label: "Inventory", href: "/admin#inventory" },
  { label: "Discounts", href: "/admin#discounts" },
  { label: "Settings", href: "/admin#settings" },
];